apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: node-express-hello-rxba
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/arewm-tenant/node-express-hello/node-express-hello-rxba@sha256:d36ae7a6871686c14e323015a8b3c16da6db00bff406251ccc12e3d3d26c5a65
        name: my-nodejs
        resources: {}
status: {}
